---
title: "The Cheat Code: Essential Math and Statistics for Social Scientists"
author: "Erik Hegelund"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
biblio-style: apalike
link-citations: yes
description: "A textbook in mathematics and statistics for social science students."
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align = "left")
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(fig.width = 5.5)
  knitr::opts_hooks$set(fig.width = function(options) {
    if (options$fig.width > 5.5) options$fig.width <- 5.5
    options
  })
}
```

# Preface {-}

This text is based on the idea that new students can benefit from learning the foundations of mathematics and statistics relatively thoroughly with a social science framework. This book is my attempt to write the introduction I wish I had received when I began my university studies.

## Why yet another textbook? {-}

This work overlaps with various others. But while most books, possibly for good reasons, choose to focus on one thing at a time, I try here to give the reader a feel for a lot of things simultaneously. I hope this combination will make it easier to see how these things are connected.

This book focuses somewhat on causal relationships - how and why things are the way they are. To do this we need to learn about the methods and conditions for causal analysis. Within social science, the methods for causal analysis have changed for the better in recent decades, and my hope is that this text will contribute to this development.

## What you will learn {-}

Part I presents the foundations of mathematics, from basic arithmetic through functions, logarithms, equations, derivatives, optimization, integration, and linear algebra. The part also contains examples of how mathematics can be used to describe theories and phenomena in social science.

Part II introduces probability theory and statistical inference. The part covers discrete and continuous probability distributions and hypothesis testing.

Part III introduces how we can study variation and covariation, the least squares method and regression analysis, with applications in social science. It also introduces counterfactual analysis and how regression analysis can be used to study causal relationships.

Part IV introduces three analytical tools commonly used in social science: Microsoft Excel, Stata, and the programming language R.

Part V contains a final chapter with some common misconceptions and suggestions for further reading.

## Thanks! {-}

This book is a development and translation (from Swedish) of [an earlier book](https://www.studentlitteratur.se/kurslitteratur/forskningsmetodik-och-vetenskapsteori/vetenskapsteori/matematik-och-statistik-for-samhallsvetare/?srsltid=AfmBOooJ12SDJRJsbUIMtBe2iEpT5dUi0qEdFDX3H0Jr2Iur0DtQOVvg) by me. I am still grateful to those who helped me create that book. Among those, a special thanks to Jakob Lundberg for help with the Laffer curve and to Fredrik Söderqvist for help with the section on monopsony.

*The author, Årsta 2026*

## License {-}

This book is published under the [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/). You are free to share and adapt the material for non-commercial purposes, provided you give appropriate credit to the author.

DOI: [10.5281/zenodo.20826595](https://doi.org/10.5281/zenodo.20826595). Report errors to hegelund.erik@gmail.com.
